### PR TITLE
Added use expire time feature for acknowledgements to IcingaWeb2

### PR DESCRIPTION
**Pull request by Massl123**
This adds #154

### CODE REVIEW

**Comment by HenriWahl** [comment]
Sorry for the late reply... I am about to get a stable release 3.4 ready and there are still some other small things to fix. I will look into your changes after this.

**Comment by Massl123** [comment]
Will this be included in 3.4? I think it would be a nice addition for that release.

**Comment by neufeind** [comment]
What does it take to get this working with an Icinga 1.x-installation as well? There is also an expiry-time when setting an ack. Inputfields on the webinterface in the HTML have these names:

<input type="checkbox" id="expire_checkbox" name="use_ack_end_time" onclick="if (document.getElementById('expire_checkbox').checked == true) document.getElementById('expired_date_row').style.display = ''; else document.getElementById('expired_date_row').style.display = 'none';">

<input type="text" class="timepicker hasDatepicker" name="end_time" value="12-02-2019 20:30:20" size="25" id="dp1575307821023">

**Comment by Massl123** [comment]
Should be pretty easy. If i find the time i can make an PR.
But this will be included in the release after 3.4.

**Pull request merged**
