### PR TITLE
Add Nagstamon RPM packages for RHEL 9 (and derivatives/clones)

### PR DESCRIPTION
**Pull request by robert-scheck**
This is a first attempt to add Nagstamon RPM packages for RHEL 9 (and derivatives/clones) - while hoping that I didn't get tricked somewhere during building and tests.

However this pull request is incomplete, because I don't know how to handle the `repo-fedora` step in `.github/workflows/build-release-{latest,stable}.yml` properly.

### CODE REVIEW

**Comment by HenriWahl** [comment]
Thanks! I will prepare the repo so RHEL packages might be included as well.

**Comment by HenriWahl** [comment]
I added extended the build pipelines to add RHEL to the repo on nagstamon.de. Can you pleae check if adding https://nagstamon.de/repo/rhel/nagstamon-latest.repo works for you?

**Comment by robert-scheck** [comment]
For some reason, the RPM from the repository depends on python3-crypto and python3-pyqt6, which both shouldn't be the case.

First is unmaintained software according to https://src.fedoraproject.org/rpms/python-crypto, second is not available, because it is too new. But from my point of view, https://github.com/HenriWahl/Nagstamon/blob/master/build/docker/Dockerfile-rhel-9 should fit. Where is my mistake?

**Comment by HenriWahl** [comment]
After the changes in https://github.com/HenriWahl/Nagstamon/commit/1f2cfcbdba0ebfaa0f67065c4732ca8fe1f5bdc9 I got it at least to install due to correct dependencies.

**Comment by robert-scheck** [comment]
Ah, thank you! And yes, the package works for me as expected on Rocky Linux 9 here.

**Pull request merged**
