### PR TITLE
add zabbix 2.4 support

### PR DESCRIPTION
**Pull request by arkadiyvleonov**

### CODE REVIEW

**Comment by HenriWahl** [comment]
Thanks!
Does this still work with older Zabbixens?

**Comment by arkadiyvleonov** [comment]
yes, work
in new API when you requesting api_version you don't need to use "auth" parameters unlike older zabbix.
may be it's not a good realisation, but it works

**Comment by arkadiyvleonov** [comment]
Sorry, I wrote not about what was the issue:
Initial value of "auth" attribute should be "None" in ZabbixAPI Class

**Comment by HenriWahl** [comment]
At https://seafile.ifw-dresden.de/d/c49b34412f/ there are Windows binaries containing this 2.4 Zabbix support - just in case someone needs them.

**Pull request merged**
