### PR TITLE
Adding support for SOCKS5 Proxy

### PR DESCRIPTION
**Pull request by justino**
When using a SOCKS5 proxy, simply set the URL to `<socks scheme>://<host>:<port>`.
Adds the following SOCKS schemes: `socks5`, `socks5h`
This requires SOCKS support in the `Requests` module using the `pysocks` module.
Added new dependencies for Debian and Redhat
Tested in Debian

I don't have access to a Redhat box to test the build process.
I also have no idea how to build this for Windows and add the new required module.

### CODE REVIEW

**Comment by HenriWahl** [comment]
That's it? Already works?

**Comment by justino** [comment]
The only thing that needs updating is the docs found at https://nagstamon.ifw-dresden.de/docs/requirements/

`pysocks` is now a requirement. So it now needs to be listed in all the pip commands, and listed in top list of pip packages

**Comment by HenriWahl** [comment]
Is this extra package available for Debian and Fedora too?

**Comment by justino** [comment]
Yes, it is.
In Debian: `python3-socks`
In Fedora: `python3-pysocks`

In the PR, I updated the appropriate build systems accordingly.

**Comment by HenriWahl** [comment]
I updated all relevant parts.

The latest binary testing version contains your addition too.

**Pull request merged**
