### PR TITLE
Initial implementation for IcingaWeb2 server class

### PR DESCRIPTION
**Pull request by minibbjd**
The IcingaWeb2 REST API is not (fully) implemented yet, so currently this implementation is limited to "view only". Once https://dev.icinga.org/issues/9606 and/or https://dev.icinga.org/issues/7300 get implemented, the action part(schedule downtime, acknowledge, etc.) can be implemented in this class.

Most changes are in the new server class file Nagstamon/Servers/IcingaWeb2.py.

I've also changed  Nagstamon/QUI/__init__.py so that it only the context menu elements are shown that are set in server.MENU_ACTIONS. This might need checking if the variable is set correctly in all other server classes.

### CODE REVIEW

**Comment by HenriWahl** [comment]
Did you already check http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/icinga2-api#icinga2-api ?

**Comment by minibbjd** [comment]
This is NOT a server class for the Icinga2 API, but for IcingaWeb2, just like the current Icinga server class is for the icinga-classic-ui.

A server class for the Icinga 2 API might be useful for some, too, but imho for most users using Nagstamon against IcingaWeb2 will be preferred. IcingaWeb2 has a pretty complete implementation for authentication (e.g. LDAP) and authorization (which users see which objects) and since most people will use these features for the IcingaWeb2 web interface anyway, it makes no sense to use the Icinga 2 API for Nagstamon.

**Comment by HenriWahl** [comment]
Isn't Icinga2 the underlaying foundation of Icinga2web? Shouldn't Icinga2 API calls influence Icinga2web?

**Comment by minibbjd** [comment]
IcingaWeb2 is written in php and has a defined, but limited API that can be accessed via the URL. I don't know how IcingaWeb2 processes API commands to Icinga2 - yes, maybe/likely through the Icinga2 API. 

Anyway, for this server class, we can only use the API that IcingaWeb2 (currently) offers. 

Accessing the Icinga2 API directly would need a setup with a different URL, username, password and port and fetching info and executing commands would need a different syntax and this would follow a different authentication/authorization scheme that IcingaWeb2. 

As such these are two separate server classes in Nagstamon.

**Comment by HenriWahl** [comment]
I did not look into any Icinga2* API so far, I just saw the comments at https://mobile.twitter.com/Nagstamon/status/703579492946673664 which point me to Icinga2.

**Comment by minibbjd** [comment]
Argh... a 3rd place to discuss.. :-)

**Comment by HenriWahl** [comment]
Gives room for every opinion... :-) but least now I get your point about the differences of both ways to talk to Icinga. The worst case will be reverse engineering the POST requests or Ajax calls of the webinterface.

**Comment by minibbjd** [comment]
My understanding is that there is no API at all in IcingaWeb2. There is an additonal module available at https://github.com/Thomas-Gelf/icingaweb2-module-deployment which only offers to schedule a downtime and which does not use the IcingaWeb2 authentication.

I've found a way to execute the needed command by analyzing the form data and making a second POST request to the same url with the necessary cgi_data. Works for recheck and acknowledge now and I will add 'Submit check result' and 'Downtime' soon.

**Comment by HenriWahl** [comment]
This is how I would do it too.

**Comment by minibbjd** [comment]
Can I expect the from start_time and end_time parameters in

_set_downtime(self, host, service, author, comment, fixed, start_time, end_time, hours, minutes):

to have a specific format? Currently the edit field is free text, but IcingaWeb2 needs something like "2016-02-28T20:03:55". I'm handling "n/a" now, but actually a datetime variable being passed, which might also be None seems to make more sense.

**Comment by HenriWahl** [comment]
What is the edit field?

**Comment by HenriWahl** [comment]
Sorry now I got it.
Every monitor server supported has some different format here - so it is no wonder that this applies here too. For other monitors like e.g. Nagios Nagstamon take the times from the parsed HTML at https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Servers/Generic.py#L458 .

**Comment by HenriWahl** [comment]
Would you mind to call this Icinga2? Or do you expect some version working with icinga2 API?

**Comment by MarcusCaepio** [comment]
I would call it Icinga2, because it uses the Icinga2 API,
How Can I test the new Nagstamon Version`?

**Comment by HenriWahl** [comment]
Just checkout https://github.com/HenriWahl/Nagstamon.git.
If you need binaries the build.py script will produce them fitting to the platform where it runs on. You might need to meet some requirements which are listed on https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by MarcusCaepio** [comment]
Die Dev Umgebung herzustellen übersteigt leider meine Programmierkenntnisse..... 
Wäre es möglich, die fertige .exe auf die Nagsta Seite zu laden?

**Comment by HenriWahl** [comment]
Eigentlich brauchst Du nur cx-freeze und InnoSetup. Ich versuche heute noch neue Binaries hochzuladen.

**Comment by minibbjd** [comment]
> Would you mind to call this Icinga2? Or do you expect some version working with icinga2 API?

It's very likely that an Icinga2 API server class will follow, but I guess the IcingaWeb2 server class is what most people want. I'm not sure which naming is better...

Approach 1: Icinga2 (this one) and Icinga2API
Approach 2: IcingaWeb2 (this one) and Icinga2

**Comment by minibbjd** [comment]
> I would call it Icinga2, because it uses the Icinga2 API,...

It does not use the Icinga2 API. It uses HTTP requests sent to the IcingaWeb2 web server.

**Comment by HenriWahl** [comment]
Most common usage will be the IcingaWeb2 interface due to the included authentication and usermanagament as you outlined before. Thus I would assume this default and call it Icinga2. If one day someone wants to add an API version (which I consider unrealistic due to your working solution) it might get an APIesque name.

**Comment by minibbjd** [comment]
Fine with me. Should I just change 

TYPE = u'IcingaWeb2'

to

TYPE = u'Icinga2'

or should the class and file name also be changed?

**Comment by HenriWahl** [comment]
I already changed all occurrences of IcingaWeb2.

**Comment by HenriWahl** [comment]
I took Icinga Web 2.2 and even login is not working apparently. Which Icinga version did you use?

**Comment by HenriWahl** [comment]
Another remark: do we need to know the server version at all? This was necessary with Icinga1 to distinguish between pure HTML to be parsed and requesting JSON. Here it should be only JSON, right?

**Comment by MarcusCaepio** [comment]
I have the current release, which came yesterday.
Version 2.2.0

**Comment by minibbjd** [comment]
I'm still on IcingaWeb 2.1.2. I'll update tomorrow and check.

Yes, it's aways json, but sooner or later different versions if IcingaWeb2 will need different handling, so I left the implementation.

**Comment by HenriWahl** [comment]
Ok, but it does not work with 2.2. I should create a 2.1 server for testing.

**Comment by HenriWahl** [comment]
Problem seems to be getting a session - maybe login changed in 2.2?

**Comment by minibbjd** [comment]
Seems like basic auth is broken in 2.2.

I've opened: https://dev.icinga.org/issues/11274

**Comment by HenriWahl** [comment]
There is a login form on the Icinga start page. Is this different to Icinga 2.1?

**Comment by minibbjd** [comment]
In 2.1, when you used basic authentication, like in my example in the issue I've opened, you were not redirected to the login page. The login page itself was also available in 2.1.

**Comment by HenriWahl** [comment]
OK, just like with Check_MK. At the moment you only support basic auth?

**Comment by HenriWahl** [comment]
Or simply always use auth page - are both ways of authentication valid and can be used in parallel?

**Comment by minibbjd** [comment]
I assume this is a bug in 2.2. If not and devs consider basic auth to be insecure and desupported it, we would need to implement cookie auth through the login page. Let's wait for feedback in the issue I created.

**Comment by HenriWahl** [comment]
In the meantime I implement cookie auth as this works well with other monitor types and is no rocket science.

**Comment by minibbjd** [comment]
Not a bug: https://dev.icinga.org/projects/icingaweb2/repository/revisions/a464e74aa42142de039600f9630f1a8ce8c40218/diff/library/Icinga/Authentication/Auth.php

Basic auth only allowed when using IcingaWeb2 API calls (which are far from being usable).

**Comment by HenriWahl** [comment]
Why oh why... give me some minutes :-)

**Comment by HenriWahl** [comment]
Added login auth in last commit ac02140c9455d80565234ff19cc5d047640ce580. Apparently works, but now I get a new error:

Traceback (most recent call last):
  File "/home/henri/Seafile/Nagstamon/Nagstamon/Servers/Icinga2.py", line 188, in _get_status_JSON
    self.new_hosts[host_name].status = self.STATES_MAPPING['hosts'][h['host_state']]
KeyError: '1'

Can you check this with your Icinga 2.1?

**Comment by minibbjd** [comment]
Strange... Works for me against 2.2.0. 

The error message looks like h['host_state'] is a string. For me it's an int, so the lookup in self.STATES_MAPPING['hosts'] works. Can you put a breakpoint there are check the types in h?

**Comment by HenriWahl** [comment]
Got it with e2f450bdece88062739c1485ceef06d57a6beb18.
STATE_MAPPING used integers but JSON broght strings
Does the latest commit e2f450bdece88062739c1485ceef06d57a6beb18 still work for you?

**Comment by HenriWahl** [comment]
If not the returned JSON values have to be converted then.

**Comment by HenriWahl** [comment]
Something seems strange: here all hosts and services are acknowledged, flapping and in downtime in Nagstamon which they are not on webinterface.

**Comment by HenriWahl** [comment]
Might have to do with misunderstood JSON values too.

**Comment by minibbjd** [comment]
No I get the error:

Traceback (most recent call last):
  File "C:/Users/Marcus.Moennig/Nagstamon\Nagstamon\Servers\Icinga2.py", line 187, in _get_status_JSON
    self.new_hosts[host_name].status = self.STATES_MAPPING['hosts'][h['host_state']]
KeyError: 1

I guess we have to typecast everything.

**Comment by HenriWahl** [comment]
You get integers and no strings? Strange. Icinga version dependent? 

I meanwhile fixed the useless extra icons - coming from strings in JSON too. This fix will be obsolete if all JSON values from Icinga will be integers where useful.

**Comment by HenriWahl** [comment]
From https://docs.python.org/3.4/library/json.html:

json.loads(s, encoding=None, cls=None, object_hook=None, parse_float=None, parse_int=None, parse_constant=None, object_pairs_hook=None, **kw)¶

    Deserialize s (a str instance containing a JSON document) to a Python object using this conversion table.
    The other arguments have the same meaning as in load(), except encoding which is ignored and deprecated.
    If the data being deserialized is not a valid JSON document, a ValueError will be raised.

Looks like this can be done easily.

**Comment by minibbjd** [comment]
Probably depends on the version of the python json library (I'm using python 3.4.3). 

Your last commit doesn't work for me:

File "C:/Users/Marcus.Moennig/Nagstamon\Nagstamon\Servers\Icinga2.py", line 187, in _get_status_JSON
    self.new_hosts[host_name].status = self.STATES_MAPPING['hosts'][h['host_state']]
KeyError: 1

I'd suggest to typecast to int here, too and change the MAPPING definitions back to int, too.

**Comment by minibbjd** [comment]
One more thing: IcingaWeb2 and Icinga2 have a service/host attribute "service_problem" and "host_problem" (click on "Problems" in the web interface). It would be nice to be able to filter for these in Nagstamon, too. The benefit is that also services/hosts that have a dependency on other hosts/services are filtered out, when the parent host/service is down. 

I didn't implement it, because it would be a filter in the filter settings dialog that would only work with Icinga 2. Wasn't sure if cluttering up the interface for just one server implementation would be the right way to go.

**Comment by HenriWahl** [comment]
OK I'll do the typecasting.
For the filter let's, see, I would like to make the basics of Icinga work first. There was somewhen a feature request about server-specific filters, maybe this would be a good place then.
Did you try to trigger some action when logged in? Did not work for me :-(

**Comment by HenriWahl** [comment]
Did the typecasting. Does it work at your setup?

**Comment by minibbjd** [comment]
Typecasting works now.

Seems like one of my commits is lost. To fix downtime action for hosts change around line 422:

        if service=='':
            formtag=pagesoup.find('form',{'name':'IcingaModuleMonitoringFormsCommandObjectScheduleHostDowntimeCommandForm'})
        else:
            formtag=pagesoup.find('form',{'name':'IcingaModuleMonitoringFormsCommandObjectScheduleServiceDowntimeCommandForm'})

The other actions seem to work just fine for me.


https://dev.icinga.org/issues/11274 indicates that all that's actually needed is 

 self.session.headers['Referer'] = 'application/json'

to qualify as an API request and use basic auth.

**Comment by HenriWahl** [comment]
I read there abaut the 'Accept' header... but well, so all the BeautifulSoup stuff for triggering actions is not necessary?

**Comment by minibbjd** [comment]
No, this is still needed. The IcingaWeb2 just call it an API call when the http header "Accept: application/json" is set. There still is no working API, so we have to parse the form tags.

When you set 

self.session.headers['Accept'] = 'application/json'

you don't have to go through the login page and work with the cookie, but can just use basic auth like in my first implementation.

**Comment by minibbjd** [comment]
Side question: For a special project at work I will need to write a server class that does no http requests, but parses a Nagios/icinga status.dat file (copied every 5 minutes from an Icinga instance in an isolated network subnet). Should I branch and request a pull or do you think this is too exotic to be included. :-)

**Comment by HenriWahl** [comment]
OK. Too late now... cookies are now accepted. :-)

Your side project sounds pretty special - maybe just fork but do not request a pull, you seem to be the only user.

**Comment by HenriWahl** [comment]
8bdc35fff2340e15a6a0943648d4ad80a53ee98d brings now display of start end times in downtime dialog

**Comment by dnsmichi** [comment]
I'd suggest to name the backend "icingaweb2" to avoid confusion with "icinga2" providing a different api. Users might not be aware of the difference, and there certainly are differences between the two products. That terminology to distinguish between the core and web is commonly used in the Icinga ecosystem. It is also to avoid questions in the community support channels :)

**Comment by HenriWahl** [comment]
OK. Are there plans to provide a fully supported Icinga2 API equivalent to the icingaWeb2 API regarding user authentication?

**Comment by dnsmichi** [comment]
Icinga 2 allows you to specify the ApiUser configuration object. You may set permissions on the specific API endpoints. If you need a more granular level, you can also add filters for these permissions. For example, you'll only allow an acknowledgement action for this specific ApiUser, but only for all hosts and services in a defined hostgroup. Or matching a custom attribute. 
If you prefer to have more than one ApiUser with a defined filter set, go for it. If you don't like basic auth but want to use an SSL certificate for client CN auth, that's also possible.

For more details please check the documentation: http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/icinga2-api#icinga2-api-permissions

**Comment by HenriWahl** [comment]
It is renamed now in commit 8fbbe360523f7b0bb288fc914cd9fd8b597b29d6.

**Comment by dnsmichi** [comment]
Thanks a lot :)

**Comment by HenriWahl** [comment]
Does the error as in https://github.com/HenriWahl/Nagstamon/issues/192 occur with IcingaWeb2 too?

**Comment by minibbjd** [comment]
I'm sick, so can't test it right now, but in my implementation I am only using service and host names and not display_name. If you haven't changed it, it should work just fine.

**Comment by HenriWahl** [comment]
But the concept of display_names exists in IcingaWeb2 too? If you do not use them I should deactivate the corresponding options in settings GUI.

**Comment by minibbjd** [comment]
Yes, see: http://docs.icinga.org/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/object-types#objecttype-service

diplay_name is not used. 

However, it would be perfect if both, display_name and service/host name would be fetched and stored, display_name would be used for displaying and the stored service/host name would be available when executing actions.

**Comment by HenriWahl** [comment]
This is how I do it now with Icinga1.
Looks like display_name is just optional or is there any default, like parity with host or service name?
I will make my current implementation more robust and adapt it to IcingaWeb2.py.

**Comment by HenriWahl** [comment]
I added display_name awareness to all IcingaWeb2 actions - maybe you could test with some real life setup if it still works and if the difference between real names and display names is recognized and treated accordingly?
Additionally I added the correct URLs for the 'Monitor' action in context menu, choosing the URLs which looked best. Can you as Icinga2 user have a look if they make sense? Thanks!

**Comment by minibbjd** [comment]
IcingaWeb2 doesn't like spaces being replaced to + signs in URLs which is what urllib.parse.urlencode does. I've changed the two calls in IcingaWeb2.py open_monitor like this:

urllib.parse.urlencode({'host': self.hosts[host].real_name})**.replace('+', ' ')**)


urllib.parse.urlencode({'host': self.hosts[host].real_name,'service': self.hosts[host].services[service].real_name})**.replace('+', ' ')**)

**Pull request merged**
