### PR TITLE
Updated code to work on OSX Yosemite

### PR DESCRIPTION
**Pull request by favoretti**
Needs `gtk-mac-integration`, but works.

### CODE REVIEW

**Comment by favoretti** [comment]
Hey,

I noticed I didn't tackle one annoying thing. Apparently, Yosemite doesn't honor `self.StatusBar.set_keep_above()`. Do you happen to know what it has been replaced with?

I'll try to tackle it coming days and will shoot in a pull request.

Thanks,
Vladimir

**Comment by HenriWahl** [comment]
Hi,
at the moment (right now) I am working at the much cleaner Qt5 port and hope I never have to care again about any GTK-related mad stuff. So I fear I am not of much help with this issue.

Regards

**Comment by HenriWahl** [comment]
Please check out https://nagstamon.ifw-dresden.de/files-nagstamon/unstable/Nagstamon-2.0-alpha.dmg which is a first alpha release of a more future-proof MacOSX-version.

**Comment by favoretti** [comment]
@HenriWahl Thanks! Passed on to our NOC team, I guess there will be quite a few volunteers to give it a spin, we use Nagstamon all the time, 24/7 :)

**Pull request merged**
