### PR TITLE
mor regex filters

### PR DESCRIPTION
**Pull request by sidharrell**
For issue
https://github.com/HenriWahl/Nagstamon/issues/544

### CODE REVIEW

**Comment by HenriWahl** [comment]
My shell's history lured me to do a forced git **push** instead a **pull** and so I overwrote you merged PR. Can you please request again?

**Comment by HenriWahl** [comment]
OK... fixed the pull/push disaster but found a bug:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/Nagstamon/QUI/__init__.py", line 4034, in get_status
    status = self.server.GetStatus()
  File "/usr/lib/python3.7/site-packages/Nagstamon/Servers/Generic.py", line 1105, in GetStatus
    if GroupsIsFilteredOutByRE(service.groups, conf) is True:
AttributeError: 'GenericService' object has no attribute 'groups'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/Nagstamon/QUI/__init__.py", line 4034, in get_status
    status = self.server.GetStatus()
  File "/usr/lib/python3.7/site-packages/Nagstamon/Servers/Generic.py", line 1105, in GetStatus
    if GroupsIsFilteredOutByRE(service.groups, conf) is True:
AttributeError: 'GenericService' object has no attribute 'groups'

Any idea?

**Comment by sidharrell** [comment]
We're using OP5. Maybe it needs the changes in that Class instead?

**Comment by HenriWahl** [comment]
Either this or GenericService just could have that extra property.

**Comment by HenriWahl** [comment]
I managed to fix the error above but found new ones:

- Please modify GUI only via .ui-files - the changes in settings_main.py are not found in settings_main.ui
- Using the Qt Creator tool there maybe would not appear glitches like these seen in the attached screenshots
settings_action_py
settings_main_py

**Comment by HenriWahl** [comment]
@sidharrell can you please provide a fixed PR using updated .ui files?

**Pull request merged**
