### PR TITLE
Centreon 2.8 beta, code refactoring

### PR DESCRIPTION
**Pull request by BenoitPoulet**
Centreon 2.8 beta
Code refactoring
Bug fixes

### CODE REVIEW

**Comment by HenriWahl** [comment]
Cool! I will merge this after release of currently stable 2.0.1.

**Comment by BenoitPoulet** [comment]
Ok, i understand.

It would be nice if you could build a beta version with this when Centreon 2.8 will be out.

**Comment by HenriWahl** [comment]
Yes, I think about going to a numbering scheme like GIMP, having even numbers for stable and odd ones for unstable/testing releases. So your changes will first go into 2.1 after this bugfix release 2.0.1 is ready - which I think it almost is.

**Comment by HenriWahl** [comment]
@BenoitPoulet I started 2.1 with your merges. What binaries do you need?

**Comment by BenoitPoulet** [comment]
Don't need to hurry, i ask them and the 2.8 release will not be out before end of november.
I just need some user's feedback to be sure that everything is fine before you next stable version.

**Pull request merged**
