### PR TITLE
quote string pushed to browser

### PR DESCRIPTION
**Pull request by theundefined**
quote string passed to browser

### CODE REVIEW

**Comment by HenriWahl** [comment]
Just out of curiosity: is there any URL not working if being not quoted?

**Comment by HenriWahl** [comment]
Just another remark: this branch is dead and just remaining for historical reasons. Please check the master branch if you want to contribute.

**Comment by theundefined** [comment]
hm... version 1.0 is no longer supported? :(


problem is discovered when i created action to create form in jira to create ticket. It works ok, if in string from nagios there is no % character (for example 90% used ;). After escaping it - it works fine.

**Comment by HenriWahl** [comment]
Please try with 2.0. Maybe your problem is gone already there.

**Comment by HenriWahl** [comment]
@theundefined did you check with Nagstamon 2.0.1?

**Pull request closed without merging**
