### PR TITLE
Incorrect display of last_check field

### PR DESCRIPTION
**Pull request by wigor2206**
The problem with incorrect display of time in the last check line is described in the request https://github.com/HenriWahl/Nagstamon/issues/1070 .
We tried to fix a few lines in the IcingaDBWeb.py file to make the display of the time of the last validation check more compact.

### CODE REVIEW

**Comment by HenriWahl** [comment]
@wigor2206  please check if latest testing build works as expected - thanks!

**Comment by wigor2206** [comment]
@HenriWahl tested. Works. But maybe you need to think about not using the utc_tim variable, but how to make it more universal

**Comment by wigor2206** [comment]
If it works out, I'll make a new PR

**Comment by HenriWahl** [comment]
> @HenriWahl tested. Works. But maybe you need to think about not using the utc_tim variable, but how to make it more universal

What do you mean exactly?

**Comment by wigor2206** [comment]
@HenriWahl 
Everything works as expected.
Should I use the latest branch or will there be a new release?

**Comment by HenriWahl** [comment]
Better stick with the latest branch, I do not know when the next release will be in sight.

**Pull request merged**
