### PR TITLE
added support for alertmanager

### PR DESCRIPTION
**Pull request by stearz**
First release of the alertmanager integration. It just supports read-access yet. Silencing of alerts in alertmanager is coming next.

### CODE REVIEW

**Comment by AIXruth** [comment]
May I please ask you to build/compile a release or upload a new version to https://nagstamon.ifw-dresden.de/download/#testing?

**Comment by HenriWahl** [comment]
> May I please ask you to build/compile a release or upload a new version to https://nagstamon.ifw-dresden.de/download/#testing?

Yes - it's there now for all platforms.

**Comment by AIXruth** [comment]
The windows version works, but already silenced alerts are still showing up. These should be filtered out by default or did I miss any option/parameter/filter for this?

**Comment by HenriWahl** [comment]
Did you activate the filter to keep them out?

**Comment by AIXruth** [comment]
To be honest, I don't know which filter I have to activate.

2020-11-18 16_35_27-Window
The picture reflects my current historical Nagios settings. Which filter rules correlates with "silenced alerts"? 
Do I have to add something to "more options" to "Map to status_information"?
2020-11-18 16_43_17-Window

**Comment by stearz** [comment]
It should already work with the "Hosts and Services down for maintenance" filter.
The filters are used globally so you didn't do anything wrong.
Can you send me a Nagstamon debug log?

**Comment by stearz** [comment]
I fixed the issue in this PR:
https://github.com/HenriWahl/Nagstamon/pull/686

**Pull request merged**
