### PR TITLE
Refactor return value of check_for_error to None for all servers

### PR DESCRIPTION
**Pull request by aleskxyz**
check_for_error function returns None but some servers are expecting boolean.
I refactor all servers to check the return value explicitly is not None

### CODE REVIEW

**Comment by aleskxyz** [comment]
I think you need to decide about the return value of this function.
In this PR you are checking that is it None or not!
https://github.com/HenriWahl/Nagstamon/pull/967

**Comment by HenriWahl** [comment]
@aleskxyz thanks for the quick look for the cause, but in most cases the condition gets quite an opposite result now:

From

```python
if errors_occured:
```
to
```python
if errors_occured is not None:
```
there is an important difference, because in the first case it will only return if True, which extends to False in the second variant. I will have to check the consequences if done globally. Maybe a s a fix it will be enough if done in Prometheus and Alertmanager.

**Comment by aleskxyz** [comment]
> @aleskxyz thanks for the quick look for the cause, but in most cases the condition gets quite an opposite result now:
> 
> From
> 
> ```python
> if errors_occured:
> ```
> 
> to
> 
> ```python
> if errors_occured is not None:
> ```
> 
> there is an important difference, because in the first case it will only return if True, which extends to False in the second variant. I will have to check the consequences if done globally. Maybe as a fix it will be enough if done in Prometheus and Alertmanager.

@HenriWahl 
I can use the first form but it seems we need to revert this PR also: https://github.com/HenriWahl/Nagstamon/pull/967

**Comment by HenriWahl** [comment]
OK, I will look for it tomorrow.

**Comment by HenriWahl** [comment]
@aleskxyz I checked it looks OK. Thanks for investigating!

**Comment by HenriWahl** [comment]
It's included now in latest release 2.13-20231031.

**Comment by HenriWahl** [comment]
Well, the whole code needs some refactoring...

**Pull request merged**
