### PR TITLE
Thruk: add disabled_backends field to filter out thruk backends (#219)

### PR DESCRIPTION
**Pull request by fermino**
This adds support for the feature asked in #219.

### CODE REVIEW

**Comment by fermino** [comment]
@HenriWahl I will need some feedback/advice as how to lay out the GUI elements (I hacked it together but pretty sure it could be better). Let me know if there's anything I can improve!

PS: Thanks for maintaining this project :)

**Comment by HenriWahl** [comment]
I fixed the GUI a little - the result should be available soon at https://github.com/HenriWahl/Nagstamon/releases/tag/latest with release 3.13-20231130

**Comment by fermino** [comment]
Sorry @HenriWahl wouldn't be necessary to merge thruk_backend into master? Do you want me to modify or test anything?

**Comment by fermino** [comment]
@HenriWahl that definitely looks better. I would just make the label `Disabled backends (comma separated IDs)` or something similar, as it might not be that intuitive to use. Otherwise it looks great!

**Pull request merged**
