### PR TITLE
change monoselection behavior to multiselection

### PR DESCRIPTION
**Pull request by Coolgeek789**
This a PR to allow multiple selection in a server :
It can handle : recheck, ack and downtime.
All other command are single selection only (as before).
I also added the ability to copy from the keyboard (ctrl+c) from all the selected line

### CODE REVIEW

**Comment by HenriWahl** [comment]
Looks cool... how exactly one can select multiple hosts/services? Pressing some key additionally?

**Comment by Coolgeek789** [comment]
left clic for selecting one or more (shift to select a range, ctrl to select one by one)
right clic for the popup menu once the selection is made

**Comment by HenriWahl** [comment]
OK... does not fully work here but looks promising :-)

**Comment by Coolgeek789** [comment]
what doesn't work ?

**Comment by HenriWahl** [comment]
right click for menu when closing window at hovering out:

`Traceback (most recent call last):
  File "/Nagstamon/Nagstamon/QUI/__init__.py", line 3330, in mouseReleaseEvent
    self.cell_clicked(index)
  File "/Nagstamon/Nagstamon/QUI/__init__.py", line 3479, in cell_clicked
    if self.miserable_service == 'Events':
AttributeError: 'TreeView' object has no attribute 'miserable_service'
`

**Comment by Coolgeek789** [comment]
yeah. I don't have check_mk so it slipped. I will change that and make a new PR

**Comment by HenriWahl** [comment]
No problem.

**Comment by Coolgeek789** [comment]
Is it OK if I make this entry in the menu available only if one row is selected ?

**Comment by HenriWahl** [comment]
Just do it - I will check later.

**Pull request merged**
